### ISSUE TITLE
Create proper PR for upstream

### ISSUE THREAD

**Issue by ineiti** [c4dt/arti#1]
* [x] Create PR against latest commit in the repo here → #2
* [x] Copy the link to the hackmd-document
* [x] @wouterl sends email with Factory in CC

**Comment by cgrigis** [comment]
After some fiddling, I managed to "simplify" it a bit and remove some of the "code deletion" (see https://github.com/c4dt/arti/tree/rework). But there is still a lot of work to do...

**Comment by cgrigis** [comment]
Changes reworked and merged in the following MR:

https://gitlab.torproject.org/tpo/core/arti/-/merge_requests/347
https://gitlab.torproject.org/tpo/core/arti/-/merge_requests/318
